# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plants.ui'
#
# Created: Sat Jun 26 17:11:48 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 676)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/res/icons/treeleaf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table = QtGui.QTableWidget(self.centralwidget)
        self.table.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table.setObjectName("table")
        self.table.setColumnCount(30)
        self.table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(29, item)
        self.verticalLayout.addWidget(self.table)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 19))
        self.menubar.setObjectName("menubar")
        self.menu_view = QtGui.QMenu(self.menubar)
        self.menu_view.setObjectName("menu_view")
        self.menu_search = QtGui.QMenu(self.menubar)
        self.menu_search.setObjectName("menu_search")
        self.menu_edit = QtGui.QMenu(self.menubar)
        self.menu_edit.setObjectName("menu_edit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(48, 48))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.action_view_name = QtGui.QAction(MainWindow)
        self.action_view_name.setCheckable(True)
        self.action_view_name.setChecked(True)
        self.action_view_name.setObjectName("action_view_name")
        self.action_view_latin = QtGui.QAction(MainWindow)
        self.action_view_latin.setCheckable(True)
        self.action_view_latin.setChecked(True)
        self.action_view_latin.setObjectName("action_view_latin")
        self.action_view_cate = QtGui.QAction(MainWindow)
        self.action_view_cate.setCheckable(True)
        self.action_view_cate.setChecked(True)
        self.action_view_cate.setObjectName("action_view_cate")
        self.action_view_shxx = QtGui.QAction(MainWindow)
        self.action_view_shxx.setCheckable(True)
        self.action_view_shxx.setChecked(True)
        self.action_view_shxx.setObjectName("action_view_shxx")
        self.action_view_size_qm = QtGui.QAction(MainWindow)
        self.action_view_size_qm.setCheckable(True)
        self.action_view_size_qm.setChecked(True)
        self.action_view_size_qm.setObjectName("action_view_size_qm")
        self.action_view_size_gf = QtGui.QAction(MainWindow)
        self.action_view_size_gf.setCheckable(True)
        self.action_view_size_gf.setChecked(True)
        self.action_view_size_gf.setObjectName("action_view_size_gf")
        self.action_view_size_gm = QtGui.QAction(MainWindow)
        self.action_view_size_gm.setCheckable(True)
        self.action_view_size_gm.setChecked(True)
        self.action_view_size_gm.setObjectName("action_view_size_gm")
        self.action_view_size_cm = QtGui.QAction(MainWindow)
        self.action_view_size_cm.setCheckable(True)
        self.action_view_size_cm.setChecked(True)
        self.action_view_size_cm.setObjectName("action_view_size_cm")
        self.action_view_size_tb = QtGui.QAction(MainWindow)
        self.action_view_size_tb.setCheckable(True)
        self.action_view_size_tb.setChecked(True)
        self.action_view_size_tb.setObjectName("action_view_size_tb")
        self.action_view_szsd = QtGui.QAction(MainWindow)
        self.action_view_szsd.setCheckable(True)
        self.action_view_szsd.setChecked(True)
        self.action_view_szsd.setObjectName("action_view_szsd")
        self.action_view_sx = QtGui.QAction(MainWindow)
        self.action_view_sx.setCheckable(True)
        self.action_view_sx.setChecked(True)
        self.action_view_sx.setObjectName("action_view_sx")
        self.action_view_gstz = QtGui.QAction(MainWindow)
        self.action_view_gstz.setCheckable(True)
        self.action_view_gstz.setChecked(True)
        self.action_view_gstz.setObjectName("action_view_gstz")
        self.action_view_hs = QtGui.QAction(MainWindow)
        self.action_view_hs.setCheckable(True)
        self.action_view_hs.setChecked(True)
        self.action_view_hs.setObjectName("action_view_hs")
        self.action_view_khlx = QtGui.QAction(MainWindow)
        self.action_view_khlx.setCheckable(True)
        self.action_view_khlx.setChecked(True)
        self.action_view_khlx.setObjectName("action_view_khlx")
        self.action_view_hq = QtGui.QAction(MainWindow)
        self.action_view_hq.setCheckable(True)
        self.action_view_hq.setChecked(True)
        self.action_view_hq.setObjectName("action_view_hq")
        self.action_view_fxbw = QtGui.QAction(MainWindow)
        self.action_view_fxbw.setCheckable(True)
        self.action_view_fxbw.setChecked(True)
        self.action_view_fxbw.setObjectName("action_view_fxbw")
        self.action_view_gq = QtGui.QAction(MainWindow)
        self.action_view_gq.setCheckable(True)
        self.action_view_gq.setChecked(True)
        self.action_view_gq.setObjectName("action_view_gq")
        self.action_view_gs = QtGui.QAction(MainWindow)
        self.action_view_gs.setCheckable(True)
        self.action_view_gs.setChecked(True)
        self.action_view_gs.setObjectName("action_view_gs")
        self.action_view_ys = QtGui.QAction(MainWindow)
        self.action_view_ys.setCheckable(True)
        self.action_view_ys.setChecked(True)
        self.action_view_ys.setObjectName("action_view_ys")
        self.action_view_zgys = QtGui.QAction(MainWindow)
        self.action_view_zgys.setCheckable(True)
        self.action_view_zgys.setChecked(True)
        self.action_view_zgys.setObjectName("action_view_zgys")
        self.action_view_zttz = QtGui.QAction(MainWindow)
        self.action_view_zttz.setCheckable(True)
        self.action_view_zttz.setChecked(True)
        self.action_view_zttz.setObjectName("action_view_zttz")
        self.action_view_gyz = QtGui.QAction(MainWindow)
        self.action_view_gyz.setCheckable(True)
        self.action_view_gyz.setChecked(True)
        self.action_view_gyz.setObjectName("action_view_gyz")
        self.action_view_nhx = QtGui.QAction(MainWindow)
        self.action_view_nhx.setCheckable(True)
        self.action_view_nhx.setChecked(True)
        self.action_view_nhx.setObjectName("action_view_nhx")
        self.action_view_sfyz = QtGui.QAction(MainWindow)
        self.action_view_sfyz.setCheckable(True)
        self.action_view_sfyz.setChecked(True)
        self.action_view_sfyz.setObjectName("action_view_sfyz")
        self.action_view_tryz = QtGui.QAction(MainWindow)
        self.action_view_tryz.setCheckable(True)
        self.action_view_tryz.setChecked(True)
        self.action_view_tryz.setObjectName("action_view_tryz")
        self.action_view_kx = QtGui.QAction(MainWindow)
        self.action_view_kx.setCheckable(True)
        self.action_view_kx.setChecked(True)
        self.action_view_kx.setObjectName("action_view_kx")
        self.action_view_ylyt = QtGui.QAction(MainWindow)
        self.action_view_ylyt.setCheckable(True)
        self.action_view_ylyt.setChecked(True)
        self.action_view_ylyt.setObjectName("action_view_ylyt")
        self.action_view_jjyt = QtGui.QAction(MainWindow)
        self.action_view_jjyt.setCheckable(True)
        self.action_view_jjyt.setChecked(True)
        self.action_view_jjyt.setObjectName("action_view_jjyt")
        self.action_view_bz = QtGui.QAction(MainWindow)
        self.action_view_bz.setCheckable(True)
        self.action_view_bz.setChecked(True)
        self.action_view_bz.setObjectName("action_view_bz")
        self.action_view_zrfbq = QtGui.QAction(MainWindow)
        self.action_view_zrfbq.setCheckable(True)
        self.action_view_zrfbq.setChecked(True)
        self.action_view_zrfbq.setObjectName("action_view_zrfbq")
        self.action_search_advance = QtGui.QAction(MainWindow)
        self.action_search_advance.setObjectName("action_search_advance")
        self.action_search_byname = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/res/icons/chinese.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_search_byname.setIcon(icon1)
        self.action_search_byname.setObjectName("action_search_byname")
        self.action_search_bylatin = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/res/icons/latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_search_bylatin.setIcon(icon2)
        self.action_search_bylatin.setObjectName("action_search_bylatin")
        self.action_edit_copy = QtGui.QAction(MainWindow)
        self.action_edit_copy.setObjectName("action_edit_copy")
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_search_byname_batch = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/res/icons/batch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_search_byname_batch.setIcon(icon3)
        self.action_search_byname_batch.setObjectName("action_search_byname_batch")
        self.action_edit_edit = QtGui.QAction(MainWindow)
        self.action_edit_edit.setEnabled(False)
        self.action_edit_edit.setObjectName("action_edit_edit")
        self.action_search_bylatin_batch = QtGui.QAction(MainWindow)
        self.action_search_bylatin_batch.setObjectName("action_search_bylatin_batch")
        self.menu_view.addAction(self.action_view_name)
        self.menu_view.addAction(self.action_view_latin)
        self.menu_view.addAction(self.action_view_cate)
        self.menu_view.addAction(self.action_view_shxx)
        self.menu_view.addAction(self.action_view_size_qm)
        self.menu_view.addAction(self.action_view_size_gf)
        self.menu_view.addAction(self.action_view_size_gm)
        self.menu_view.addAction(self.action_view_size_cm)
        self.menu_view.addAction(self.action_view_size_tb)
        self.menu_view.addAction(self.action_view_szsd)
        self.menu_view.addAction(self.action_view_sx)
        self.menu_view.addAction(self.action_view_gstz)
        self.menu_view.addAction(self.action_view_hs)
        self.menu_view.addAction(self.action_view_khlx)
        self.menu_view.addAction(self.action_view_hq)
        self.menu_view.addAction(self.action_view_fxbw)
        self.menu_view.addAction(self.action_view_gq)
        self.menu_view.addAction(self.action_view_gs)
        self.menu_view.addAction(self.action_view_ys)
        self.menu_view.addAction(self.action_view_zgys)
        self.menu_view.addAction(self.action_view_zttz)
        self.menu_view.addAction(self.action_view_gyz)
        self.menu_view.addAction(self.action_view_nhx)
        self.menu_view.addAction(self.action_view_sfyz)
        self.menu_view.addAction(self.action_view_tryz)
        self.menu_view.addAction(self.action_view_kx)
        self.menu_view.addAction(self.action_view_ylyt)
        self.menu_view.addAction(self.action_view_jjyt)
        self.menu_view.addAction(self.action_view_bz)
        self.menu_view.addAction(self.action_view_zrfbq)
        self.menu_search.addAction(self.action_search_byname)
        self.menu_search.addAction(self.action_search_bylatin)
        self.menu_search.addAction(self.action_search_byname_batch)
        self.menu_search.addAction(self.action_search_bylatin_batch)
        self.menu_search.addAction(self.action_search_advance)
        self.menu_edit.addAction(self.action_edit_copy)
        self.menu_edit.addAction(self.action_edit_edit)
        self.menubar.addAction(self.menu_search.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "树种小全", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "树种名", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "拉丁学名", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "科名", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "生活习性", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "乔木(米)", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "冠幅(米)", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "灌木(米)", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "丛木(米)", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "藤本(米)", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("MainWindow", "生长速度", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("MainWindow", "树形(成年树)", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("MainWindow", "观赏特征", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(12).setText(QtGui.QApplication.translate("MainWindow", "花色", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(13).setText(QtGui.QApplication.translate("MainWindow", "开花类型", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(14).setText(QtGui.QApplication.translate("MainWindow", "花期(月)", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(15).setText(QtGui.QApplication.translate("MainWindow", "芳香部位", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(16).setText(QtGui.QApplication.translate("MainWindow", "果期(熟)", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(17).setText(QtGui.QApplication.translate("MainWindow", "果色(熟)", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(18).setText(QtGui.QApplication.translate("MainWindow", "叶色(供观赏)", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(19).setText(QtGui.QApplication.translate("MainWindow", "枝干颜色", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(20).setText(QtGui.QApplication.translate("MainWindow", "枝条特征", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(21).setText(QtGui.QApplication.translate("MainWindow", "光因子", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(22).setText(QtGui.QApplication.translate("MainWindow", "耐寒性", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(23).setText(QtGui.QApplication.translate("MainWindow", "水分因子", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(24).setText(QtGui.QApplication.translate("MainWindow", "土壤因子", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(25).setText(QtGui.QApplication.translate("MainWindow", "抗性", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(26).setText(QtGui.QApplication.translate("MainWindow", "园林用途", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(27).setText(QtGui.QApplication.translate("MainWindow", "经济用途", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(28).setText(QtGui.QApplication.translate("MainWindow", "备注", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(29).setText(QtGui.QApplication.translate("MainWindow", "自然分布区", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_view.setTitle(QtGui.QApplication.translate("MainWindow", "显示列", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_search.setTitle(QtGui.QApplication.translate("MainWindow", "搜索", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_edit.setTitle(QtGui.QApplication.translate("MainWindow", "编辑", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_name.setText(QtGui.QApplication.translate("MainWindow", "树种名", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_latin.setText(QtGui.QApplication.translate("MainWindow", "拉丁学名", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_cate.setText(QtGui.QApplication.translate("MainWindow", "科名", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_shxx.setText(QtGui.QApplication.translate("MainWindow", "生活习性", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_size_qm.setText(QtGui.QApplication.translate("MainWindow", "乔木(米)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_size_gf.setText(QtGui.QApplication.translate("MainWindow", "冠幅(米)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_size_gm.setText(QtGui.QApplication.translate("MainWindow", "灌木(米)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_size_cm.setText(QtGui.QApplication.translate("MainWindow", "丛木(米)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_size_tb.setText(QtGui.QApplication.translate("MainWindow", "藤本(米)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_szsd.setText(QtGui.QApplication.translate("MainWindow", "生长速度", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_sx.setText(QtGui.QApplication.translate("MainWindow", "树形(成年树)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_gstz.setText(QtGui.QApplication.translate("MainWindow", "观赏特征", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_hs.setText(QtGui.QApplication.translate("MainWindow", "花色", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_khlx.setText(QtGui.QApplication.translate("MainWindow", "开花类型", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_hq.setText(QtGui.QApplication.translate("MainWindow", "花期(月)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_fxbw.setText(QtGui.QApplication.translate("MainWindow", "芳香部位", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_gq.setText(QtGui.QApplication.translate("MainWindow", "果期(熟)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_gs.setText(QtGui.QApplication.translate("MainWindow", "果色(熟)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_ys.setText(QtGui.QApplication.translate("MainWindow", "叶色(供观赏)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_zgys.setText(QtGui.QApplication.translate("MainWindow", "枝干颜色", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_zttz.setText(QtGui.QApplication.translate("MainWindow", "枝条特征", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_gyz.setText(QtGui.QApplication.translate("MainWindow", "光因子", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_nhx.setText(QtGui.QApplication.translate("MainWindow", "耐寒性", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_sfyz.setText(QtGui.QApplication.translate("MainWindow", "水分因子", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_tryz.setText(QtGui.QApplication.translate("MainWindow", "土壤因子", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_kx.setText(QtGui.QApplication.translate("MainWindow", "抗性", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_ylyt.setText(QtGui.QApplication.translate("MainWindow", "园林用途", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_jjyt.setText(QtGui.QApplication.translate("MainWindow", "经济用途", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_bz.setText(QtGui.QApplication.translate("MainWindow", "备注", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_zrfbq.setText(QtGui.QApplication.translate("MainWindow", "自然分布区", None, QtGui.QApplication.UnicodeUTF8))
        self.action_search_advance.setText(QtGui.QApplication.translate("MainWindow", "高级查询", None, QtGui.QApplication.UnicodeUTF8))
        self.action_search_byname.setText(QtGui.QApplication.translate("MainWindow", "按中文名搜索", None, QtGui.QApplication.UnicodeUTF8))
        self.action_search_byname.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.action_search_bylatin.setText(QtGui.QApplication.translate("MainWindow", "按拉丁名搜索", None, QtGui.QApplication.UnicodeUTF8))
        self.action_search_bylatin.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.action_edit_copy.setText(QtGui.QApplication.translate("MainWindow", "复制", None, QtGui.QApplication.UnicodeUTF8))
        self.action_edit_copy.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("MainWindow", "批量查询植物信息", None, QtGui.QApplication.UnicodeUTF8))
        self.action_search_byname_batch.setText(QtGui.QApplication.translate("MainWindow", "按中文名批量搜索", None, QtGui.QApplication.UnicodeUTF8))
        self.action_search_byname_batch.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.action_edit_edit.setText(QtGui.QApplication.translate("MainWindow", "修改", None, QtGui.QApplication.UnicodeUTF8))
        self.action_search_bylatin_batch.setText(QtGui.QApplication.translate("MainWindow", "按拉丁名批量搜索", None, QtGui.QApplication.UnicodeUTF8))
        self.action_search_bylatin_batch.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))

import image_rc
